#!/bin/bash

whofile=$(whoami)
if [ "$whofile" != "root" ]
then
        echo "You must be root"
        exit 1
fi
echo -n "user : "
read user
userdel -f $user
if [ 0 = $? ]
then
        echo "User $user deleted"
fi
